### ISSUE TITLE
Using you script without Let's Encrypt

### ISSUE THREAD

**Issue by Orion-Omega** [Destripador/docker-nextcloud-onlyoffice#2]
I would like to use your script, but since I use an internal IP 192.168.1.x instead of a domain, how should I proceed to use a Self-Signed certificate instead?

Thank you!

**Comment by Destripador** [comment]
To be able to use it with an IP, you need to disable lets encrypt in docker-compose.yml
Commenting is enough

FILE:  .docker-compose.yml

```
######## LET'S ENCRYPT ########
#  letsencrypt-companion:
#    image: nginxproxy/acme-companion
#    container_name: letsencrypt-companion
#    volumes_from:
#      - proxy
#    volumes:
#      - /var/run/docker.sock:/var/run/docker.sock:ro
#      - ./config/proxy/certs:/etc/nginx/certs:rw
#      - ./config/acme:/etc/acme.sh
#    restart: always
#    depends_on:
#      - proxy

```
Add the IP from which you will enter the nginx configuration file:

FILE: ./config/nginx/web.env
```

VIRTUAL_HOST=<YOUR IP>
LETSENCRYPT_HOST=
LETSENCRYPT_EMAIL=

```
and finally add the IP to the trusted domains

FILE: ./nextcloud/config/config.php 

```
  'trusted_domains' =>
  array (
    0 => 'localhost',
    1 => '<YOUR IP>'
  ),
```
